config/routes.rb
Rails.application.routes.draw do
  # get 'bookings/new'
  #  get "cre",to: 'bookings#create'
  root 'flights#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights
  resources :bookings
  # Defines the root path route ("/")
  # root "articles#index"
  get "all",to: 'flights#show'
  resources :airport
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
    has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class 
  
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passangers
    accepts_nested_attributes_for :passangers

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  

  has_many :bookings 
  has_many :passangers, through: :bookings
end

app/models/passanger.rb
class Passanger < ApplicationRecord
    belongs_to :booking
    has_many :flights , through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
 def index
  @bookings = Booking.all
 end
 
  def new
    @booking = Booking.new
    @seat = params[:seats].to_i
    
   @seat.times{ @booking.passangers.build}
    @flights = Flight.find_by(params[:flight_id])
    
  end

  def create
    @flights = Flight.find_by(params[:flight_id])
   
    @booking = Booking.new(booking_params)
   
    if @booking.save
      flash[:notice] =  "Bookings Successfull! "
      TicketMailer.with(booking: @booking).booking_mail.deliver_now!
      redirect_to booking_path(@booking)
    else
      render :new,status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
  def booking_params

      params.require(:booking).permit(:flight_id,{passangers_attributes: [:passanger_id,:passanger_id,:name,:email]})
  end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index

    @flights = Flight.all
    @avail_flights = Flight.where(arrival_airport_id: params[:arrival_airport_id],departure_airport_id: params[:departure_airport_id] )

     
    
    
    @flight_options= Airport.all.map{ |u| [ u.airport_name,u.id ] }
    @flight_options1 = Flight.all.map{|f| [f.flight_date,f.flight_date]}
    
    # @avail_f  light = Flight.select(arrival_airport :params[:sri])
   
  end

  def show

  @flights = Flight.all

  end
  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Fill your details</h1>
<%= form_with model: @booking,method: :post,html:{"data-turbo" => false} do |form| %>
 <%x=1%>

 <%=form.fields_for :passangers do |f|%>
  <div> 
 
    <%= "Passenger #{x}" %><br />
   <%=f.label :name%>
   <%=f.text_field :name%>
   </div>

<div>
   <%=f.label :email%>
   <%=f.text_field :email%>
   
</div>
<%x+=1%>
<%end%>
<%= form.hidden_field :flight_id, value: params[:flight_id] %>

<%=form.submit "Search" %>

<% end %>

  

app/views/bookings/show.html.erb
<section class="hero is-fullheight is-light is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="column is-half is-offset-one-quarter">
        <h1 class="title">
          Trip summary
        </h1>
        <h2 class="subtitle">
     
         <%= @booking.flight.flight_date.strftime('%d %B %Y') %>
        </h2>
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th>Departure</th>
              <th>Arrival</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @booking.flight.departure_airport.airport_name%> <%= @booking.flight.flight_date.strftime('%H:%M') %></td>
              <td><%= @booking.flight.arrival_airport.airport_name %> <%= (@booking.flight.flight_date + (@booking.flight.flight_duration/60).to_i.hours).strftime('%H:%M') %></td>
            </tr>
          </tbody>
        </table>

         <h1 class="title">
          Passenger details
        </h1>
        <table class="table is-fullwidth has-text-left">
          <thead>
            <tr>
              <th>Passenger name</th>
            </tr>
          </thead>
          <tbody>
          <% @booking.passangers.each_with_index do |passenger, idx| %>
            <tr>
              <td><%= passenger.name %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
  
        <h1 class="title">
          Contact details
        </h1>
        <table class="table is-fullwidth has-text-left">
          <thead>
            <tr>
              <th>Passenger name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
          <% @booking.passangers.each_with_index do |passenger, idx| %>
            <tr>
              <td><%= passenger.name %></td>
              <td><%= passenger.email %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
  
        <%= link_to 'Book more flights', root_path, class: "button is-large is-dark is-outlined" %>

      </div>
    </div>
  </div>



      
  
       

      </div>
    </div>
  </div>
</section>
  









<!--
<%x=1%>
<% @booking.passangers.each do |f| %>

<h5><%= "   #{x} Passenger" %></h5>
<h6>Name: <%=f.name%></h6>
 
 <h6>Email: <%=f.email%></h6>
 
 <%x= x+ 1%>
<%end%>
<br>
<section>
 <%= link_to 'Book more flights', root_path, class: "button is-large is-dark is-outlined" %>
</section>
-->

app/views/flights/_form.html.erb
<h1 class="title is-3">Book a Flight</h1>

<%= form_with model: @flight,method: :get do |f| %>
   
<h4>From
<%= f.select :departure_airport_id, options_for_select(@flight_options)%></h4>
<h4>To
<%= f.select :arrival_airport_id, options_for_select(@flight_options) %>
</h4>
<h4>Date 
<%=f.select :date,options_for_select(@flight_options1)%>
</h4>
<h4>
Number of Seats:
<%=f.select :seats,[1,2,3,4,5,6]%>
</h4>
<%=f.submit "Search" %>


<% end %>

  

  
   

app/views/flights/_searchresult.html.erb
  <h2 class="title is-4">Search results</h2>

 
<% if @avail_flights.any? %>
  
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Flight No.</th>
          <th>Departure Airport</th>
          <th>Arrival Airport</th>
          <th>Date</th>
          <th>Departs at</th>
          <th>Flight Duration</th>
          <th>Book your Ticket<th>
          
         
        </tr>
      </thead>
      <tbody>
        <% @avail_flights.each do |flight| %>
          <tr>
            <td><%= flight.id %></td>
            <td><%= flight.departure_airport.airport_name %> </td>
            <td><%= flight.arrival_airport.airport_name %></td>
            <td><%= flight.flight_date.strftime('%F') %></td>
            <td><%= flight.flight_date.strftime('%H:%M') %></td>
            <td><%= flight.flight_duration %> minutes</td>
              <td><%= link_to "Book",new_booking_path(flight_id: flight.id,seats:params[:seats])%></td>
         
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Sorry there are no flights available for your search. 😞</p>
  <% end %>
  
  <!--
  <% if @avail_flights.any? %>
  
    <table class="table">
      <thead>
        <tr>
          <th>Flight No.</th>
          <th>Departure Airport</th>
          <th>Arrival Airport</th>
          <th>Date</th>
          <th>Departs at</th>
          
         
        </tr>
      </thead>
      <tbody>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.id %></td>
            <td><%= flight.departure_airport.airport_name %> </td>
            <td><%= flight.arrival_airport.airport_name %></td>
            <td><%= flight.flight_date.strftime('%F') %></td>
            <td><%= flight.flight_date.strftime('%H:%M') %></td>
            <td><%= flight.flight_duration %> minutes</td>
         
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Sorry there are no flights available for your search. 😞</p>
  <% end %>
-->

app/views/flights/index.html.erb
<div>


<div>

</div>
<%= render "form"%>
<div>
<%= render "searchresult" %>
</div>

</div>

app/views/flights/show.html.erb
 
<% if @flights.any? %>
  
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Flight No.</th>
          <th>Departure Airport</th>
          <th>Arrival Airport</th>
          <th>Date</th>
          <th>Departs at</th>
          <th>Flight Duration</th>
            <th>Book your Ticket<th>
          
         
        </tr>
      </thead>
      <tbody>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.id %></td>
            <td><%= flight.departure_airport.airport_name %> </td>
            <td><%= flight.arrival_airport.airport_name %></td>
            <td><%= flight.flight_date.strftime('%F') %></td>
            <td><%= flight.flight_date.strftime('%H:%M') %></td>
            <td><%= flight.flight_duration %> minutes</td>
          <%# <td><%= link_to "Book",new_booking_path(flight_id: flight.id,seats:params[:seats])%></td> %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Sorry there are no flights available for your search. 😞</p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JAIHIND</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%=render partial: "shared/navbar"%>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" >

  <%=link_to "Odin Flight Booker" ,root_path,class: "navbar-brand"%>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     
      <li class="nav-item">
      <%=link_to "Bookings",root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
      <%=link_to "All Flights",all_path, class: "nav-link"%>
      </li>
     
    </ul>

   
 

  </div>

</nav>